[package]
name = "doenermann-bot"
version = "2.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { version = "0.12.5", default-features = false, features = [
    "client",
    "chrono",
    "gateway",
    "rustls_backend",
    "model",
] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"
serde = "1.0"
toml = "1.1.2"
light-magic = "0.8.4"
reqwest = { version = "0.13.3", features = ["json"] }
url = { version = "2.5.8", features = ["serde"] }
