[bot]
# The Bot Token
token = ""
# A date format used for dates inside the bot messages, default is `%d.%m.%Y`
date_format = "%d.%m.%Y"
# A timestamp format used for displaying timestamps inside the copied messages file, default is `%Y-%m-%d %H:%M:%S UTC`
timestamp_format = "%Y-%m-%d %H:%M:%S UTC"

[paths]
# Path to the birthdays file
birthdays = "birthdays.csv"
# Path to the messages file
messages = "citations.txt"

[server]
# Id of the copy channel
copy_channel = ""
# Id of the role which should be added on join
role_on_join = ""
# Id of the bot's admin, can be multiple
admins = [ "" ]
