[bot]
# The Bot Token
token = ""
# A date format used for displaying dates inside the bot messages, default is `%d.%m.%Y`
date_format = "%d.%m.%Y"
# A timestamp format used for displaying timestamps inside the bot messages, default is `%d.%m.%Y %H:%M:%S`
timestamp_format = "%d.%m.%Y %H:%M:%S"

[paths]
# Path to the database file
database = "db.json"

[server]
# Id of the server
guild = ""
# Id of the citations channel
citations_channel = ""
# Id of the role which should be added on join
role_on_join = ""
# Id of the bot's admin, can be multiple
admins = [ "" ]
